apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sender-backend-pdb
  namespace: sender
spec:
  # Usar maxUnavailable en lugar de minAvailable para permitir 0 r√©plicas
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sender-backend
      tier: backend

